### ISSUE TITLE
Breaks two-finger back/forward swipes on OS X 10.7/Chrome 21

### ISSUE THREAD

**Issue by e0da** [e0da/smooth_scrollerator#4]
So the skinny is that two-finger back/forward swipes on OS X 10.7/Chrome 21 are broken. I bet the bug is not limited to Chrome 2.1 or OS X 10.7. I'll address this during the rewrite. ...if I can get my hands on a Mac.

Original report from the [silly Chrome feedback interface](https://chrome.google.com/webstore/support/lmicgfcegednlkdhgbhgickcgndjeeig?hl=en&gl=US#bug):

> Posted by Sébastien G. - 4 Sep 2012
> I use the magic trackpad on Mac OS 10.7 with Chrome 21 .... I can with
> two fingers zwipe left and right to go back and forward ... and with
> your appli this function doesn't works ...
> Thank You
> 
> Posted by Sébastien G. - Sep 6, 2012
> Hello Justin, ..
> Okay.. thanks for your answer.. anyway other programs (Smart Scroll on
> web) have problems with chrome ..... Good Luck
> 
> Posted by Justin Force - Sep 4, 2012
> Thank you for your feedback! I'll do what I can to fix it. I don't own a
> Mac and the codebase needs some major overhauling anyway, so I don't
> know when this will work.

**Comment by k76765754** [comment]
yes，I have this problem too !
