### ISSUE TITLE
Smooth Scrollerator and images

### ISSUE THREAD

**Issue by pmuttley** [e0da/smooth_scrollerator#6]
Greetings

I'm using Smooth Scrollerator with Chrome 22 (and Windows 7 Pro) and I noticed a problem when clicking a image (from blogger, for example) to see in full size. The website turns black, there's the "X" button on the corner but the image didn't appear. Turning off the plugin, everything works fine.

This issue also happens with Smooth Scroll.

Thanks for the attention

**Comment by e0da** [comment]
I've never seen this behavior. I would need a link to an affected page to
reproduce the problem in order to investigate it.

Thanks for taking the time to report it. I just need a little more
information.

Justin

**Comment by pmuttley** [comment]
Hi Justin, thanks for your reply!

So, here's a simple example:
http://delphisempre.blogspot.com.br/2012/07/exemplo-de-aplicacao-para-dar-um-zoom_24.html

There's a small picture in this post. Try to click on it with SS enabled. Here I got only an empty black screen. If you disable SS, restart Chrome and click again on this picture, it will appears up the black screen.

Let me know if I'm not crazy!

Thanks again!

**Comment by Danny-Rodriguez** [comment]
I can confirm this behavior with blogspot

**Comment by e0da** [comment]
The error is occuring inside of this incomprehensible line of JavaScript from [this file](http://www.blogger.com/static/v1/jsbin/408492008-lbx_pt-BR.js).

> Uncaught TypeError: Cannot call method 'q' of undefined

``` javascript
B.gX=function(){this.Gb.Ec(BW);this.a5()};B.a5=function(){var a=this.Ia.getPosition().Bc;this.Gu.dispatchEvent(new jV(WU,a,this.qa.C(a).C().Ke().q()||h,this.qa.C(a).q()))};var J2=function(a,b,d){GW.call(this,new JW(a));this.j_=b;this.Q=NM(a);this.$b(1);b=this.W;b.JH(430);b.zK(660);this.fe=new I2(a,d);b.ka(this.fe);this.Fb=a.get(JM)};I(J2,GW);B=J2.prototype;B.fZ=N&&!ZI(Ie);B.ra=function(){J2.c.ra.call(this);var a=this.p();this.Zm=a.createElement(t);this.Zm.className=ei;this.Q.U(oC)||S(this.Zm,fi);a.Mv(this.Zm,this.W.a())};B.O=function(){J2.c.O.call(this);this.I().j(this.a(),mv,this.RQ).j(this.fe,B2,this.Kk).j(this.Fb,FW,this.Kk)};
```

I don't know if I can do anything about this. As I refactor Smooth Scrollerator, I will make my best effort to make it completely unobtrusive. Ideally, it shouldn't interact with any other scripts, but there may be some interesting injection and event manipulation going on.

Thank you @pmuttley and @Z-Overlord for reporting and confirming this behavior. I will see what I can do to fix it as I find time.
