### ISSUE TITLE
Twitter's website does not load new content when scrolling down with the mouse wheel.

### ISSUE THREAD

**Issue by pragmatrix** [e0da/smooth_scrollerator#7]
I had this problem since a few days and today I selectively disabled my extensions and found out that it was caused by smooth_scrollerator. Can someone reproduce this?

**Comment by e0da** [comment]
Thanks for using the extension and for participating on GitHub, @pragmatrix! I appreciate it.

I have not experienced this issue. Please share more about your environment. What's your OS? Chrome version? Extension version? Have you tried enabling only this extension? (bad behavior may be interaction with another unrelated extension)

Thanks!
Justin

**Comment by pragmatrix** [comment]
Hey @justinforce, I am using Chrome 25.0.1364.97 m on Windows 8 64-bit, Scrollerator 1.1.5. And yes, that also happens when the only extension is Scrollerator (tested in an incognito tab).

**Comment by e0da** [comment]
I don't use this extension anymore. Seems like Chrome finally smooth scrolls by default. I'm closing all issues on this extension. I hope that some folks got some good use out of it. :)
